spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testdb
      username: test
      password: test123
  freemarker:
    cache: false
  thymeleaf:
    cache: false

server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl